### PR TITLE
adding support for discussions

### PR DESCRIPTION
**Pull request by kbrashears5**

### CODE REVIEW

**Comment by kbrashears5** [comment]
waiting for [api](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#update-a-repository) docs to be updated do include discussions

**Comment by kbrashears5** [comment]
This PR has not received a response in a timely manner. If you still think there is a problem, please leave a comment to avoid the PR from automatically closing.

**Comment by kbrashears5** [comment]
This PR has been automatically closed. Please create a new PR or reopen this one.

**Comment by ghost** [comment]
This PR has not received a response in a timely manner. If you still think there is a problem, please leave a comment to avoid the PR from automatically closing.

**Comment by kbrashears5** [comment]
Waiting on GitHub

**Comment by ghost** [comment]
This PR has not received a response in a timely manner. If you still think there is a problem, please leave a comment to avoid the PR from automatically closing.

**Comment by ghost** [comment]
This PR has been automatically closed. Please create a new PR or reopen this one.

**Comment by ghost** [comment]
This PR has not received a response in a timely manner. If you still think there is a problem, please leave a comment to avoid the PR from automatically closing.

**Comment by ghost** [comment]
This PR has been automatically closed. Please create a new PR or reopen this one.

**Pull request closed without merging**
