### PR TITLE
Update endpoint to get all repositories

### PR DESCRIPTION
**Pull request by tenshiAMD**
This is to support getting all repositories whether it is public or private using GitHub API as an authenticated user.

### CODE REVIEW

**Comment by tenshiAMD** [comment]
@kbrashears5 hi please check this PR which probably resolves this [issue](https://github.com/kbrashears5/github-action-repo-settings-sync/issues/3). I hope this helps. Thank you.

**Review by kbrashears5 — CHANGES_REQUESTED** [review]
when I first read through the authenticated user docs I didn't think it would work because it would return things that you only had read to and fail trying to update those.

Reading through again I think it will work, I think you just need to add `?affiliation=owner` as a query string parameter. That way, none of the functionality changes as I think owner is the same as if you did `/users/${user}/repos`.

get that fixed, otherwise looks good

**Comment by tenshiAMD** [comment]
@kbrashears5 I'm done with the changes you requested. Please check. Thank you.

**Review by kbrashears5 — APPROVED** [review]

**Comment by tenshiAMD** [comment]
@kbrashears5 thanks for merging and hoping this update will be released soon so we can give it a try. Thanks again!

**Comment by tenshiAMD** [comment]
@kbrashears5 this is great! I just to wanna inform you this is a success when I use `master` in our config file.

**Pull request merged**
