### PR TITLE
Add support for auto-merge configuration

### PR DESCRIPTION
**Pull request by domdomegg**
Adds support for [auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) configuration.

The [update a repository endpoint](https://docs.github.com/en/rest/reference/repos#update-a-repository) has been updated to accept a `allow_auto_merge` parameter, which this PR uses.

### CODE REVIEW

**Comment by domdomegg** [comment]
I think the semantic versioning has got a bit muddled. I think this should be released as version 1.2.0, given 1.1.0 was branch protection rules.

**Comment by domdomegg** [comment]
Requesting review from @kbrashears5

**Comment by kbrashears5** [comment]
sorry @domdomegg, haven't been on in a while. thanks for the improvement, changes look good

**Comment by domdomegg** [comment]
No worries, thanks for merging and releasing a new version 🙌

**Pull request merged**
